name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "pipeline-tests"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: MacOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: 'Release'
          combine: true
          cli: 'latest'
          target: ${{ matrix.config.target }}

  package-deploy:
    name: Package & Deploy Builds
    runs-on: ubuntu-latest
    needs: ['build']
    environment:
      name: release
      url: ${{ steps.deploy-release.outputs.binary-url }}
    steps:
      - name: Combine builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GDIntercept Build
          path: ${{ steps.build.outputs.build-output }}

      - name: Deploy release
        id: deploy-release
        uses: binary-locker/bin-pipe/binary@main
        with:
          binary-output: ${{ steps.build.outputs.build-output }}
          api-domain: 'https://bin.smjsproductions.com'
          api-username: ${{ secrets.BINPIPE_API_USERNAME }}
          api-key: ${{ secrets.BINPIPE_API_KEY }}

  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-latest
    environment:
      name: pages
      url: ${{ steps.deploy-pages.outputs.pages-url }}
    steps:
      - name: Deploy to Binary Locker
        id: deploy-pages
        uses: binary-locker/bin-pipe/pages@main
        with:
          api-domain: 'https://bin.smjsproductions.com'
          api-username: ${{ secrets.BINPIPE_API_USERNAME }}
          api-key: ${{ secrets.BINPIPE_API_KEY }}
          pages-directory: docs